services:
#  webapplication1:
#    image: webapplication1
#    build:
#      context: .
#      dockerfile: WebApplication1/Dockerfile

  postgres:
    image: postgres:alpine
    container_name: postgres-example-laravel-some-idea
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5435:5432
    volumes:
      - ./docker/my-db:/var/lib/postgresql/data
    restart: unless-stopped
